package edit;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import java.time.LocalDate;
import java.time.Month;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class edit_melos extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public edit_melos() {
        initComponents();
        addDataToJComboBoxId();
    }
    static String driverClassName = "oracle.jdbc.OracleDriver";
    static String url = "jdbc:oracle:thin:@192.168.6.21:1521:dblabs";
    static Connection dbConnection = null;
    static String username = "it185192";
    static String passwd = "giorgosgtav";

    static PreparedStatement pstatement = null;

    static Statement statement = null;
    static ResultSet rs = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelMelos = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jComboBoxId = new javax.swing.JComboBox<>();
        jLabelOnoma = new javax.swing.JLabel();
        jTextFieldOnoma = new javax.swing.JTextField();
        jLabelEponimo = new javax.swing.JLabel();
        jTextFieldEponimo = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelTilefono = new javax.swing.JLabel();
        jTextFieldTilefono = new javax.swing.JTextField();
        jLabelDieyuinsi = new javax.swing.JLabel();
        jTextFieldDieyuinsi = new javax.swing.JTextField();
        jLabelHmerominiaGenisis = new javax.swing.JLabel();
        jComboBoxHmeresGennisis = new javax.swing.JComboBox<>();
        jComboBoxMinesGennisis = new javax.swing.JComboBox<>();
        jComboBoxXroniaGennisis = new javax.swing.JComboBox<>();
        jLabelHmerominiaEgrafis = new javax.swing.JLabel();
        jComboBoxHmeresEgrafis = new javax.swing.JComboBox<>();
        jComboBoxMinesEgrafis = new javax.swing.JComboBox<>();
        jComboBoxXroniaEgrafis = new javax.swing.JComboBox<>();
        jButtonEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ΕΠΕΞΕΡΓΑΣΙΑ ΜΕΛΟΥΣ");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabelMelos.setText("ΕΠΕΞΕΡΓΑΣΙΑ ΜΕΛΟΥΣ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jLabelMelos, gridBagConstraints);

        jLabelId.setText("ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jLabelId, gridBagConstraints);

        jComboBoxId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIdActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jComboBoxId, gridBagConstraints);

        jLabelOnoma.setText("Όνομα:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jLabelOnoma, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jTextFieldOnoma, gridBagConstraints);

        jLabelEponimo.setText("Επώνυμο:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jLabelEponimo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jTextFieldEponimo, gridBagConstraints);

        jLabelEmail.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jLabelEmail, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jTextFieldEmail, gridBagConstraints);

        jLabelTilefono.setText("Τηλέφωνο:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jLabelTilefono, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jTextFieldTilefono, gridBagConstraints);

        jLabelDieyuinsi.setText("Διεύθυνση:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jLabelDieyuinsi, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jTextFieldDieyuinsi, gridBagConstraints);

        jLabelHmerominiaGenisis.setText("Ημερομηνία γέννησης:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jLabelHmerominiaGenisis, gridBagConstraints);

        jComboBoxHmeresGennisis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBoxHmeresGennisis.setSelectedIndex(-1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jComboBoxHmeresGennisis, gridBagConstraints);

        jComboBoxMinesGennisis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ιανουάριος", "Φεβρουάριος", "Μάρτιος ", "Απρίλιος ", "Μάιος ", "Ιούνιος", "Ιούλιος", "Αύγουστος ", "Σεπτέμβριος", "Οκτώβριος ", "Νοέμβριος", "Δεκέμβριος" }));
        jComboBoxMinesGennisis.setSelectedIndex(-1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jComboBoxMinesGennisis, gridBagConstraints);

        jComboBoxXroniaGennisis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900\t", "1901\t", "1902\t", "1903\t", "1904\t", "1905\t", "1906\t", "1907\t", "1908\t", "1909", "1910\t\t", "1911\t", "1912\t", "1913\t", "1914\t", "1915\t", "1916\t", "1917\t", "1918\t", "1919", "1920\t", "1921\t", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953\t", "1954", "1955", "1956", "1957", "1958", "1959", "1960\t", "1961\t", "1962\t", "1963\t", "1964\t", "1965\t", "1966\t", "1967\t", "1968\t", "1969", "1970\t", "1971\t", "1972\t", "1973\t", "1974\t", "1975\t", "1976\t", "1977\t", "1978\t", "1979", "1980\t", "1981\t", "1982\t", "1983\t", "1984\t", "1985\t", "1986\t", "1987\t", "1988\t", "1989", "1990\t", "1991\t", "1992\t", "1993\t", "1994\t", "1995\t", "1996\t", "1997\t", "1998\t", "1999", "2000\t", "2001\t", "2002\t", "2003\t", "2004\t", "2005\t", "2006\t", "2007\t", "2008\t", "2009", "2010\t", "2011\t", "2012\t", "2013\t", "2014\t", "2015\t", "2016\t", "2017\t", "2018\t", "2019", "2020\t", "2021", " " }));
        jComboBoxXroniaGennisis.setSelectedIndex(-1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jComboBoxXroniaGennisis, gridBagConstraints);

        jLabelHmerominiaEgrafis.setText("Ημερομηνία εγγραφής:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jLabelHmerominiaEgrafis, gridBagConstraints);

        jComboBoxHmeresEgrafis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBoxHmeresEgrafis.setSelectedIndex(-1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jComboBoxHmeresEgrafis, gridBagConstraints);

        jComboBoxMinesEgrafis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ιανουάριος", "Φεβρουάριος", "Μάρτιος ", "Απρίλιος ", "Μάιος ", "Ιούνιος", "Ιούλιος", "Αύγουστος ", "Σεπτέμβριος", "Οκτώβριος ", "Νοέμβριος", "Δεκέμβριος" }));
        jComboBoxMinesEgrafis.setSelectedIndex(-1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jComboBoxMinesEgrafis, gridBagConstraints);

        jComboBoxXroniaEgrafis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900\t", "1901\t", "1902\t", "1903\t", "1904\t", "1905\t", "1906\t", "1907\t", "1908\t", "1909", "1910\t\t", "1911\t", "1912\t", "1913\t", "1914\t", "1915\t", "1916\t", "1917\t", "1918\t", "1919", "1920\t", "1921\t", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953\t", "1954", "1955", "1956", "1957", "1958", "1959", "1960\t", "1961\t", "1962\t", "1963\t", "1964\t", "1965\t", "1966\t", "1967\t", "1968\t", "1969", "1970\t", "1971\t", "1972\t", "1973\t", "1974\t", "1975\t", "1976\t", "1977\t", "1978\t", "1979", "1980\t", "1981\t", "1982\t", "1983\t", "1984\t", "1985\t", "1986\t", "1987\t", "1988\t", "1989", "1990\t", "1991\t", "1992\t", "1993\t", "1994\t", "1995\t", "1996\t", "1997\t", "1998\t", "1999", "2000\t", "2001\t", "2002\t", "2003\t", "2004\t", "2005\t", "2006\t", "2007\t", "2008\t", "2009", "2010\t", "2011\t", "2012\t", "2013\t", "2014\t", "2015\t", "2016\t", "2017\t", "2018\t", "2019", "2020\t", "2021" }));
        jComboBoxXroniaEgrafis.setSelectedIndex(-1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jComboBoxXroniaEgrafis, gridBagConstraints);

        jButtonEdit.setText("Επεξεργασία");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jButtonEdit, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        LocalDate gennisi = LocalDate.of(jComboBoxXroniaGennisis.getSelectedIndex()+1900,
                Month.of(jComboBoxMinesGennisis.getSelectedIndex()+1),
                jComboBoxHmeresGennisis.getSelectedIndex()+1);
        Date dategennisi = Date.valueOf(gennisi);
        
        LocalDate egrafi=  LocalDate.of(jComboBoxXroniaEgrafis.getSelectedIndex()+1900,
                Month.of(jComboBoxMinesEgrafis.getSelectedIndex()+1),
                jComboBoxHmeresEgrafis.getSelectedIndex()+1);
        Date dateegrafi = Date.valueOf(egrafi);
        
        try {
            editMelos(Integer.parseInt((String)jComboBoxId.getSelectedItem()),
                    jTextFieldOnoma.getText(),
                    jTextFieldEponimo.getText(),
                    jTextFieldEmail.getText(),
                    Integer.parseInt(jTextFieldTilefono.getText()),
                    jTextFieldDieyuinsi.getText(),
                    dategennisi,
                    dateegrafi);
            JOptionPane.showMessageDialog(null, "Επιτυχής επεξεργασία");
        } catch (Exception ex) {
            Logger.getLogger(edit_melos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    Object rowData[] = new Object[600];
    int i = 0;
    int numberOfColumns = 0;

    private void jComboBoxIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIdActionPerformed
        // TODO add your handling code here:
        int j,x;
        String hmerominia;
        for (j = 0; j <= i;) {
            if (jComboBoxId.getSelectedItem() == rowData[j]) {
                jTextFieldOnoma.setText((String) rowData[j + 1]);
                jTextFieldEponimo.setText((String) rowData[j + 2]);
                jTextFieldEmail.setText((String) rowData[j + 3]);
                jTextFieldTilefono.setText((String) rowData[j + 4]);
                jTextFieldDieyuinsi.setText((String) rowData[j + 5]);
                
                hmerominia=(String) rowData[j + 6];
                
                for (x = 1900; x <= 2021;x++) {
                    if (hmerominia.substring(0,4).equals(String.valueOf(x))){
                        jComboBoxXroniaGennisis.setSelectedIndex(x-1900);
                    }
                }
                
                for (x = 1; x <= 12;x++) {
                    if (hmerominia.substring(5,7).equals(String.valueOf(x)) || hmerominia.substring(6,7).equals(String.valueOf(x))){
                        jComboBoxMinesGennisis.setSelectedIndex(x-1);
                    }
                }

                for (x = 1; x <= 31;x++) {
                    if (hmerominia.substring(8,10).equals(String.valueOf(x)) || hmerominia.substring(9,10).equals(String.valueOf(x))){
                        jComboBoxHmeresGennisis.setSelectedIndex(x-1);
                    }
                } 
                //-------------------------------------------------------------------------------------------------------------------------------------
                hmerominia=(String) rowData[j + 7];
                for (x = 1900; x <= 2021;x++) {
                    if (hmerominia.substring(0,4).equals(String.valueOf(x))){
                        jComboBoxXroniaEgrafis.setSelectedIndex(x-1900);
                    }
                }
                for (x = 1; x <= 12;x++) {
                    if (hmerominia.substring(5,7).equals(String.valueOf(x)) || hmerominia.substring(6,7).equals(String.valueOf(x))){
                        jComboBoxMinesEgrafis.setSelectedIndex(x-1);
                    }
                }
                for (x = 1; x <= 31;x++) {
                    if (hmerominia.substring(8,10).equals(String.valueOf(x)) || hmerominia.substring(9,10).equals(String.valueOf(x))){
                        jComboBoxHmeresEgrafis.setSelectedIndex(x-1);
                    }
                }
            }
            j = j + numberOfColumns;
        }

    }//GEN-LAST:event_jComboBoxIdActionPerformed

    public void editMelos(int id,String onoma,String eponimo,String email,int tilefono,String dieyuinsi,Date gennisi,Date egrafi) throws Exception {
        Class.forName(driverClassName);
        dbConnection = DriverManager.getConnection(url, username, passwd);

        pstatement = dbConnection.prepareStatement("BEGIN UPDATE_MELOS (?,?,?,?,?,?,?,?); END;");
        pstatement.setInt(1, id);
        pstatement.setString(2, onoma);
        pstatement.setString(3, eponimo);
        pstatement.setString(4, email);
        pstatement.setInt(5, tilefono);
        pstatement.setString(6, dieyuinsi);
        pstatement.setDate(7, gennisi);
        pstatement.setDate(8, egrafi);

        pstatement.executeUpdate();

        pstatement.close();
        dbConnection.close();
    }

    void addDataToJComboBoxId() {
        DefaultComboBoxModel ComboBox = (DefaultComboBoxModel) jComboBoxId.getModel();

        try {
            dbConnection = DriverManager.getConnection(url, username, passwd);
            statement = dbConnection.createStatement();
            rs = statement.executeQuery("SELECT * FROM TABLE (EMFANISIMELOS)");
            ResultSetMetaData rsmd = rs.getMetaData();
            numberOfColumns = rsmd.getColumnCount();
            while (rs.next()) {
                rowData[i] = rs.getString(1);
                i++;
                rowData[i] = rs.getString(2);
                i++;
                rowData[i] = rs.getString(3);
                i++;
                rowData[i] = rs.getString(4);
                i++;
                rowData[i] = rs.getString(5);
                i++;
                rowData[i] = rs.getString(6);
                i++;
                rowData[i] = rs.getString(7);
                i++;
                rowData[i] = rs.getString(8);
                i++;
            }
        } catch (SQLException ex) {
            System.out.println("\n -- SQL Exception --- \n");
            while (ex != null) {
                System.out.println("Melos Message: " + ex.getMessage());
                ex = ex.getNextException();
            }
        }
        jComboBoxId.addItem("");
        int j;
        for (j = 0; j < i;) {
            ComboBox.addElement(rowData[j]);
            j = j + numberOfColumns;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_melos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_melos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_melos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_melos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_melos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JComboBox<String> jComboBoxHmeresEgrafis;
    private javax.swing.JComboBox<String> jComboBoxHmeresGennisis;
    private javax.swing.JComboBox<String> jComboBoxId;
    private javax.swing.JComboBox<String> jComboBoxMinesEgrafis;
    private javax.swing.JComboBox<String> jComboBoxMinesGennisis;
    private javax.swing.JComboBox<String> jComboBoxXroniaEgrafis;
    private javax.swing.JComboBox<String> jComboBoxXroniaGennisis;
    private javax.swing.JLabel jLabelDieyuinsi;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEponimo;
    private javax.swing.JLabel jLabelHmerominiaEgrafis;
    private javax.swing.JLabel jLabelHmerominiaGenisis;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelMelos;
    private javax.swing.JLabel jLabelOnoma;
    private javax.swing.JLabel jLabelTilefono;
    private javax.swing.JTextField jTextFieldDieyuinsi;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEponimo;
    private javax.swing.JTextField jTextFieldOnoma;
    private javax.swing.JTextField jTextFieldTilefono;
    // End of variables declaration//GEN-END:variables
}
