package emfanisi;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import main.main;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class emfanisi extends javax.swing.JFrame {

    /**
     * Creates new form insert
     */
    public emfanisi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelEmfanisi = new javax.swing.JLabel();
        jButtonMelos = new javax.swing.JButton();
        jButtonProsopiko = new javax.swing.JButton();
        jButtonRafiera = new javax.swing.JButton();
        jButtonBiblio = new javax.swing.JButton();
        jButtonDanismos = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonPiso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ΕΜΦΑΝΙΣΗ");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabelEmfanisi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelEmfanisi.setText("ΕΜΦΑΝΙΣΗ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jLabelEmfanisi, gridBagConstraints);

        jButtonMelos.setText("Μέλος");
        jButtonMelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMelosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jButtonMelos, gridBagConstraints);

        jButtonProsopiko.setText("Προσωπικό");
        jButtonProsopiko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProsopikoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jButtonProsopiko, gridBagConstraints);

        jButtonRafiera.setText("Ραφιέρα");
        jButtonRafiera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRafieraActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jButtonRafiera, gridBagConstraints);

        jButtonBiblio.setText("Βιβλίο");
        jButtonBiblio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBiblioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jButtonBiblio, gridBagConstraints);

        jButtonDanismos.setText("Δανεισμός");
        jButtonDanismos.setToolTipText("");
        jButtonDanismos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDanismosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jButtonDanismos, gridBagConstraints);

        jButtonExit.setText("Έξοδος");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jButtonExit, gridBagConstraints);

        jButtonPiso.setText("Πίσω");
        jButtonPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPisoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jButtonPiso, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMelosActionPerformed
        // TODO add your handling code here:
        emfanisi_melos me = new emfanisi_melos();
        me.setVisible(true);
    }//GEN-LAST:event_jButtonMelosActionPerformed

    private void jButtonProsopikoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProsopikoActionPerformed
        // TODO add your handling code here:
        emfanisi_prosopiko pr = new emfanisi_prosopiko();
        pr.setVisible(true);
    }//GEN-LAST:event_jButtonProsopikoActionPerformed

    private void jButtonRafieraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRafieraActionPerformed
        // TODO add your handling code here:
        emfanisi_rafiera ra = new emfanisi_rafiera();
        ra.setVisible(true);
    }//GEN-LAST:event_jButtonRafieraActionPerformed

    private void jButtonBiblioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBiblioActionPerformed
        // TODO add your handling code here:
        emfanisi_biblio bi = new emfanisi_biblio();
        bi.setVisible(true);
    }//GEN-LAST:event_jButtonBiblioActionPerformed

    private void jButtonDanismosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDanismosActionPerformed
        // TODO add your handling code here:
        emfanisi_danismos da = new emfanisi_danismos();
        da.setVisible(true);
    }//GEN-LAST:event_jButtonDanismosActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Θέλετε σίγουρα να κλείσετε την εφαρμογή;", "Confirm", JOptionPane.YES_NO_OPTION);
        if (a == 0)
            System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPisoActionPerformed
        // TODO add your handling code here:
        close();
        main ma = new main();
        ma.setVisible(true);
    }//GEN-LAST:event_jButtonPisoActionPerformed

    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emfanisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emfanisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emfanisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emfanisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emfanisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBiblio;
    private javax.swing.JButton jButtonDanismos;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonMelos;
    private javax.swing.JButton jButtonPiso;
    private javax.swing.JButton jButtonProsopiko;
    private javax.swing.JButton jButtonRafiera;
    private javax.swing.JLabel jLabelEmfanisi;
    // End of variables declaration//GEN-END:variables
}
