package insert;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.time.LocalDate;
import java.time.Month;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class insert_danismos extends javax.swing.JFrame {

    /**
     * Creates new form Danismos
     */
    public insert_danismos() {
        initComponents();
        addDataToJComboBoxIdMelos();
        addDataToJComboBoxIsbn();
        addDataToJComboBoxIdProsopiko();
    }

    static String driverClassName = "oracle.jdbc.OracleDriver";
    static String url = "jdbc:oracle:thin:@192.168.6.21:1521:dblabs";
    static Connection dbConnection = null;
    static String username = "it185192";
    static String passwd = "giorgosgtav";

    static PreparedStatement pstatement = null;

    static Statement statement = null;
    static ResultSet rs = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelDanismos = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabelIsbn = new javax.swing.JLabel();
        jComboBoxIsbn = new javax.swing.JComboBox<>();
        jLabelIdMelos = new javax.swing.JLabel();
        jComboBoxIdMelos = new javax.swing.JComboBox<>();
        jLabelIdProsopikoy = new javax.swing.JLabel();
        jComboBoxIdProsopiko = new javax.swing.JComboBox<>();
        jLabelHmerominiaDanismoy = new javax.swing.JLabel();
        jComboBoxHmeresDanismoy = new javax.swing.JComboBox<>();
        jComboBoxMinesDanismoy = new javax.swing.JComboBox<>();
        jComboBoxXroniaDanismoy = new javax.swing.JComboBox<>();
        jLabelHmerominiaEpistrofis = new javax.swing.JLabel();
        jComboBoxHmeresEpistrofis = new javax.swing.JComboBox<>();
        jComboBoxMinesEpistrofis = new javax.swing.JComboBox<>();
        jComboBoxXroniaEpistrofis = new javax.swing.JComboBox<>();
        jButtonIpoboli = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ΕΙΣΑΓΩΓΗ ΔΑΝΕΙΣΜΟΥ");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabelDanismos.setText("ΕΙΣΑΓΩΓΗ ΔΑΝΕΙΣΜΟΥ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jLabelDanismos, gridBagConstraints);

        jLabelID.setText("ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jLabelID, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jTextFieldId, gridBagConstraints);

        jLabelIsbn.setText("ISBN:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jLabelIsbn, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jComboBoxIsbn, gridBagConstraints);

        jLabelIdMelos.setText("ID Μέλους:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jLabelIdMelos, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jComboBoxIdMelos, gridBagConstraints);

        jLabelIdProsopikoy.setText("ID Προσωπικό:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jLabelIdProsopikoy, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jComboBoxIdProsopiko, gridBagConstraints);

        jLabelHmerominiaDanismoy.setText("Ημερομηνία δανεισμού:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 20, 20);
        getContentPane().add(jLabelHmerominiaDanismoy, gridBagConstraints);

        jComboBoxHmeresDanismoy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBoxHmeresDanismoy.setSelectedIndex(-1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jComboBoxHmeresDanismoy, gridBagConstraints);

        jComboBoxMinesDanismoy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ιανουάριος", "Φεβρουάριος", "Μάρτιος ", "Απρίλιος ", "Μάιος ", "Ιούνιος", "Ιούλιος", "Αύγουστος ", "Σεπτέμβριος", "Οκτώβριος ", "Νοέμβριος", "Δεκέμβριος" }));
        jComboBoxMinesDanismoy.setSelectedIndex(-1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jComboBoxMinesDanismoy, gridBagConstraints);

        jComboBoxXroniaDanismoy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900\t", "1901\t", "1902\t", "1903\t", "1904\t", "1905\t", "1906\t", "1907\t", "1908\t", "1909", "1910\t\t", "1911\t", "1912\t", "1913\t", "1914\t", "1915\t", "1916\t", "1917\t", "1918\t", "1919", "1920\t", "1921\t", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953\t", "1954", "1955", "1956", "1957", "1958", "1959", "1960\t", "1961\t", "1962\t", "1963\t", "1964\t", "1965\t", "1966\t", "1967\t", "1968\t", "1969", "1970\t", "1971\t", "1972\t", "1973\t", "1974\t", "1975\t", "1976\t", "1977\t", "1978\t", "1979", "1980\t", "1981\t", "1982\t", "1983\t", "1984\t", "1985\t", "1986\t", "1987\t", "1988\t", "1989", "1990\t", "1991\t", "1992\t", "1993\t", "1994\t", "1995\t", "1996\t", "1997\t", "1998\t", "1999", "2000\t", "2001\t", "2002\t", "2003\t", "2004\t", "2005\t", "2006\t", "2007\t", "2008\t", "2009", "2010\t", "2011\t", "2012\t", "2013\t", "2014\t", "2015\t", "2016\t", "2017\t", "2018\t", "2019", "2020\t", "2021" }));
        jComboBoxXroniaDanismoy.setSelectedIndex(-1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jComboBoxXroniaDanismoy, gridBagConstraints);

        jLabelHmerominiaEpistrofis.setText("Ημερομηνία επιστροφής:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jLabelHmerominiaEpistrofis, gridBagConstraints);

        jComboBoxHmeresEpistrofis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBoxHmeresEpistrofis.setSelectedIndex(-1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jComboBoxHmeresEpistrofis, gridBagConstraints);

        jComboBoxMinesEpistrofis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ιανουάριος", "Φεβρουάριος", "Μάρτιος ", "Απρίλιος ", "Μάιος ", "Ιούνιος", "Ιούλιος", "Αύγουστος ", "Σεπτέμβριος", "Οκτώβριος ", "Νοέμβριος", "Δεκέμβριος" }));
        jComboBoxMinesEpistrofis.setSelectedIndex(-1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jComboBoxMinesEpistrofis, gridBagConstraints);

        jComboBoxXroniaEpistrofis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900\t", "1901\t", "1902\t", "1903\t", "1904\t", "1905\t", "1906\t", "1907\t", "1908\t", "1909", "1910\t\t", "1911\t", "1912\t", "1913\t", "1914\t", "1915\t", "1916\t", "1917\t", "1918\t", "1919", "1920\t", "1921\t", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953\t", "1954", "1955", "1956", "1957", "1958", "1959", "1960\t", "1961\t", "1962\t", "1963\t", "1964\t", "1965\t", "1966\t", "1967\t", "1968\t", "1969", "1970\t", "1971\t", "1972\t", "1973\t", "1974\t", "1975\t", "1976\t", "1977\t", "1978\t", "1979", "1980\t", "1981\t", "1982\t", "1983\t", "1984\t", "1985\t", "1986\t", "1987\t", "1988\t", "1989", "1990\t", "1991\t", "1992\t", "1993\t", "1994\t", "1995\t", "1996\t", "1997\t", "1998\t", "1999", "2000\t", "2001\t", "2002\t", "2003\t", "2004\t", "2005\t", "2006\t", "2007\t", "2008\t", "2009", "2010\t", "2011\t", "2012\t", "2013\t", "2014\t", "2015\t", "2016\t", "2017\t", "2018\t", "2019", "2020\t", "2021" }));
        jComboBoxXroniaEpistrofis.setSelectedIndex(-1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 50);
        getContentPane().add(jComboBoxXroniaEpistrofis, gridBagConstraints);

        jButtonIpoboli.setText("Υποβολή");
        jButtonIpoboli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIpoboliActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jButtonIpoboli, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIpoboliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIpoboliActionPerformed
        // TODO add your handling code here:
        try {
            if (!jTextFieldId.getText().isBlank() && jComboBoxIdMelos.getSelectedIndex() != -1 && jComboBoxIdProsopiko.getSelectedIndex() != -1 && jComboBoxIsbn.getSelectedIndex() != -1) {
                LocalDate danismoy = LocalDate.of(jComboBoxXroniaDanismoy.getSelectedIndex() + 1900,
                        Month.of(jComboBoxMinesDanismoy.getSelectedIndex() + 1),
                        jComboBoxHmeresDanismoy.getSelectedIndex() + 1);
                Date datedanismoy = Date.valueOf(danismoy);

                LocalDate epistrofi = LocalDate.of(jComboBoxXroniaEpistrofis.getSelectedIndex() + 1900,
                        Month.of(jComboBoxMinesEpistrofis.getSelectedIndex() + 1),
                        jComboBoxHmeresEpistrofis.getSelectedIndex() + 1);
                Date dateepistrofi = Date.valueOf(epistrofi);

                insertDanismos(Integer.parseInt(jTextFieldId.getText()),
                        Integer.parseInt((String) jComboBoxIdMelos.getSelectedItem()),
                        Integer.parseInt((String) jComboBoxIdProsopiko.getSelectedItem()),
                        Integer.parseInt((String) jComboBoxIsbn.getSelectedItem()),
                        datedanismoy,
                        dateepistrofi);
                JOptionPane.showMessageDialog(null, "Επιτυχής εισαγωγή");
                jTextFieldId.setText("");
                jComboBoxHmeresDanismoy.setSelectedIndex(-1);
                jComboBoxHmeresEpistrofis.setSelectedIndex(-1);
                jComboBoxIdMelos.setSelectedIndex(-1);
                jComboBoxIdProsopiko.setSelectedIndex(-1);
                jComboBoxIsbn.setSelectedIndex(-1);
                jComboBoxMinesDanismoy.setSelectedIndex(-1);
                jComboBoxMinesEpistrofis.setSelectedIndex(-1);
                jComboBoxXroniaDanismoy.setSelectedIndex(-1);
                jComboBoxXroniaEpistrofis.setSelectedIndex(-1);
            } else {
                JOptionPane.showMessageDialog(null, "Τα πεδία ID, ID Μελους, ID Προσοπικου, ISBN ειναι υποχρεωτικά");
            }
        } catch (Exception ex) {
            Logger.getLogger(insert_danismos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonIpoboliActionPerformed

    public void insertDanismos(int id, int idmelos, int idprosopiko, int isbn, Date danismoy, Date epistrofi) throws Exception {
        Class.forName(driverClassName);
        dbConnection = DriverManager.getConnection(url, username, passwd);

        pstatement = dbConnection.prepareStatement("BEGIN INSERT_DANISMOS(?,?,?,?,?,?); END;");
        pstatement.setInt(1, id);
        pstatement.setInt(2, idmelos);
        pstatement.setInt(3, idprosopiko);
        pstatement.setInt(4, isbn);
        pstatement.setDate(5, danismoy);
        pstatement.setDate(6, epistrofi);

        pstatement.executeUpdate();

        pstatement.close();
        dbConnection.close();
    }

    void addDataToJComboBoxIdMelos() {
        DefaultComboBoxModel ComboBox = (DefaultComboBoxModel) jComboBoxIdMelos.getModel();

        Object rowData[] = new Object[50];

        int i = 0;
        try {
            dbConnection = DriverManager.getConnection(url, username, passwd);
            statement = dbConnection.createStatement();
            rs = statement.executeQuery("SELECT * FROM TABLE (EMFANISIMELOS)");
            while (rs.next()) {
                rowData[i] = rs.getString(1);
                i++;
            }
        } catch (SQLException ex) {
            System.out.println("\n -- SQL Exception --- \n");
            while (ex != null) {
                System.out.println("Melos Message: " + ex.getMessage());
                ex = ex.getNextException();
            }
        }
        jComboBoxIdMelos.addItem("");
        int j;
        for (j = 0; j < i; j++) {
            ComboBox.addElement(rowData[j]);
        }
    }

    void addDataToJComboBoxIsbn() {
        DefaultComboBoxModel ComboBox = (DefaultComboBoxModel) jComboBoxIsbn.getModel();

        Object rowData[] = new Object[50];

        int i = 0;
        try {
            dbConnection = DriverManager.getConnection(url, username, passwd);
            statement = dbConnection.createStatement();
            rs = statement.executeQuery("SELECT * FROM TABLE (EMFANISIBIBLIO)");
            while (rs.next()) {
                rowData[i] = rs.getString(1);
                i++;
            }
        } catch (SQLException ex) {
            System.out.println("\n -- SQL Exception --- \n");
            while (ex != null) {
                System.out.println("Isbn Message: " + ex.getMessage());
                ex = ex.getNextException();
            }
        }
        jComboBoxIsbn.addItem("");
        int j;
        for (j = 0; j < i; j++) {
            ComboBox.addElement(rowData[j]);
        }
    }

    void addDataToJComboBoxIdProsopiko() {
        DefaultComboBoxModel ComboBox = (DefaultComboBoxModel) jComboBoxIdProsopiko.getModel();

        Object rowData[] = new Object[50];

        int i = 0;
        try {
            dbConnection = DriverManager.getConnection(url, username, passwd);
            statement = dbConnection.createStatement();
            rs = statement.executeQuery("SELECT * FROM TABLE (EMFANISIPROSOPIKO)");
            while (rs.next()) {
                rowData[i] = rs.getString(1);
                i++;
            }
        } catch (SQLException ex) {
            System.out.println("\n -- SQL Exception --- \n");
            while (ex != null) {
                System.out.println("Prosopiko Message: " + ex.getMessage());
                ex = ex.getNextException();
            }
        }
        jComboBoxIdProsopiko.addItem("");
        int j;
        for (j = 0; j < i; j++) {
            ComboBox.addElement(rowData[j]);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insert_danismos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insert_danismos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insert_danismos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insert_danismos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insert_danismos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIpoboli;
    private javax.swing.JComboBox<String> jComboBoxHmeresDanismoy;
    private javax.swing.JComboBox<String> jComboBoxHmeresEpistrofis;
    private javax.swing.JComboBox<String> jComboBoxIdMelos;
    private javax.swing.JComboBox<String> jComboBoxIdProsopiko;
    private javax.swing.JComboBox<String> jComboBoxIsbn;
    private javax.swing.JComboBox<String> jComboBoxMinesDanismoy;
    private javax.swing.JComboBox<String> jComboBoxMinesEpistrofis;
    private javax.swing.JComboBox<String> jComboBoxXroniaDanismoy;
    private javax.swing.JComboBox<String> jComboBoxXroniaEpistrofis;
    private javax.swing.JLabel jLabelDanismos;
    private javax.swing.JLabel jLabelHmerominiaDanismoy;
    private javax.swing.JLabel jLabelHmerominiaEpistrofis;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelIdMelos;
    private javax.swing.JLabel jLabelIdProsopikoy;
    private javax.swing.JLabel jLabelIsbn;
    private javax.swing.JTextField jTextFieldId;
    // End of variables declaration//GEN-END:variables
}
